models:
  qwen3-14:
    model_name: qwen3:14b
    api_base: http://localhost:11434/v1
    api_key: ollama
  qwen3-8:
    model_name: qwen3:8b
    api_base: http://localhost:11434/v1
    api_key: ollama
  qwen3-4:
    model_name: qwen3:4b-instruct
    api_base: http://localhost:11434/v1
    api_key: ollama
  qwen3-30-a6b:
    model_name: "hf.co/mradermacher/Qwen3-30B-A6B-16-Extreme-GGUF:Q8_0"
    api_base: http://localhost:11434/v1
    api_key: ollama
  qwen3-30:
    model_name: "hf.co/unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q8_K_XL"
    api_base: http://localhost:11434/v1
    api_key: ollama
model_choices:
  orchestration: qwen3-30-a6b
  code_analysis: qwen3-30-a6b
  code_writing: qwen3-30-a6b
  context_summarization: qwen3-30-a6b
